// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef apt_notifier_h
#define apt_notifier_h
#include <FL/Fl.H>
#include <string>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *main_window;
#include <FL/Fl_Output.H>
extern Fl_Output *cmd_op;
#include <FL/Fl_Button.H>
extern Fl_Double_Window *done_window;
#include <FL/Fl_Box.H>
void CB_Button(Fl_Widget*, void*);
void Exit_button(Fl_Widget*, void*);
#endif
