// generated by Fast Light User Interface Designer (fluid) version 1.0304

#include "apt-notifier.h"
#include <stdio.h>
using namespace std;

static string popenStdout(string cmd) {
  string data;
  FILE* stream;
  const int max_buffer = 256;
  char buffer[max_buffer];
  cmd.append(" 2>&1");
  
  stream = popen(cmd.c_str(), "r");
  
  if (stream) {
  	while (!feof(stream)) {
  		if (fgets(buffer, max_buffer, stream) != NULL)
  			data.append(buffer);	
  	}
  	pclose(stream);
  }
  
  return data;
}

Fl_Double_Window *main_window=(Fl_Double_Window *)0;

Fl_Output *cmd_op=(Fl_Output *)0;

Fl_Double_Window *done_window=(Fl_Double_Window *)0;

int main(int argc, char **argv) {
  { main_window = new Fl_Double_Window(915, 495, "System Upgrader");
    main_window->color((Fl_Color)38);
    { cmd_op = new Fl_Output(0, 25, 915, 360);
      cmd_op->box(FL_FLAT_BOX);
      cmd_op->color((Fl_Color)35);
      cmd_op->labelsize(12);
      cmd_op->labelcolor(FL_BACKGROUND2_COLOR);
      cmd_op->textsize(12);
      cmd_op->textcolor(FL_BACKGROUND2_COLOR);
    } // Fl_Output* cmd_op
    { Fl_Button* o = new Fl_Button(250, 425, 95, 20, "Upgrade");
      o->box(FL_FLAT_BOX);
      o->color((Fl_Color)33);
      o->labelsize(12);
      o->labelcolor(FL_BACKGROUND2_COLOR);
      o->callback((Fl_Callback*)CB_Button);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(555, 425, 95, 20, "Cancel");
      o->box(FL_FLAT_BOX);
      o->color((Fl_Color)33);
      o->labelsize(12);
      o->labelcolor(FL_BACKGROUND2_COLOR);
      o->callback((Fl_Callback*)Exit_button);
    } // Fl_Button* o
    main_window->end();
  } // Fl_Double_Window* main_window
  { done_window = new Fl_Double_Window(485, 100, "Sucessfully upgraded");
    done_window->color((Fl_Color)38);
    done_window->labelcolor((Fl_Color)38);
    { Fl_Button* o = new Fl_Button(200, 65, 70, 20, "OK");
      o->box(FL_FLAT_BOX);
      o->color(FL_FOREGROUND_COLOR);
      o->labelcolor(FL_BACKGROUND2_COLOR);
      o->callback((Fl_Callback*)Exit_button);
    } // Fl_Button* o
    { Fl_Box* o = new Fl_Box(225, 28, 35, 17, "Sucessfully upgraded the system, you may restart the system");
      o->labelcolor(FL_BACKGROUND2_COLOR);
    } // Fl_Box* o
    done_window->end();
  } // Fl_Double_Window* done_window
  string out = popenStdout("apt-get -o DEbug::NoLocking=true --trivial-only -V dist-upgrade");
  if (out.find("0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.") != string::npos){
    exit(0);
  }
  cmd_op->value(out.c_str());
  main_window->show();
  return Fl::run();
}

void CB_Button(Fl_Widget*, void*) {
  main_window->hide();
  system("pkexec apt-get dist-upgrade -y");
  done_window->show();
}

void Exit_button(Fl_Widget*, void*) {
  exit(0);
}
